In [6]:
import sys

!{sys.executable} -m pip install xgboost catboost

Requirement already satisfied: xgboost in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (3.3.0)
Requirement already satisfied: catboost in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (1.2.10)
Requirement already satisfied: numpy in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (from xgboost) (2.5.0)
Requirement already satisfied: scipy in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (from xgboost) (1.18.0)
Requirement already satisfied: graphviz in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (from catboost) (3.11.0)
Requirement already satisfied: pandas<4.0,>=0.24 in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (from catboost) (3.0.3)
Requirement already satisfied: plotly in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (from catboost) (6.8.0)
Requirement already satisfied: six in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=9 in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (from matplotlib->catboost) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: narwhals>=1.15.1 in /Users/apple/Documents/RezoX/.venv/lib/python3.12/site-packages (from plotly->catboost) (2.22.1)

In [7]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

from pathlib import Path

import joblib

from sklearn.model_selection import train_test_split

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor


from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [8]:
DATA_PATH = Path("../data/processed/featured_data.csv")

df = pd.read_csv(DATA_PATH)

df.head()

              area_type location  total_sqft  bath  balcony  price  bhk
0  Super built-up  Area    Other      5000.0   9.0      3.0  360.0   11
1  Super built-up  Area    Other      6000.0  12.0      2.0  150.0   11
2  Super built-up  Area    Other      1800.0   1.0      1.0  200.0    1
3            Plot  Area    Other      2360.0   4.0      1.0  650.0    4
4  Super built-up  Area    Other      5425.0  13.0      0.0  275.0   13

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8119 entries, 0 to 8118
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   area_type   8119 non-null   str
 1   location    8119 non-null   str
 2   total_sqft  8119 non-null   float64
 3   bath        8119 non-null   float64
 4   balcony     8119 non-null   float64
 5   price       8119 non-null   float64
 6   bhk         8119 non-null   int64
dtypes: float64(4), int64(1), str(2)
memory usage: 444.1 KB

In [10]:
X = df.drop(columns=[
    "price",
])

y = df["price"]

In [11]:
print(X.columns)

Index(['area_type', 'location', 'total_sqft', 'bath', 'balcony', 'bhk'], dtype='str')

In [12]:
categorical_columns = X.select_dtypes(include="object").columns

categorical_columns

Index(['area_type', 'location'], dtype='str')

In [13]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_columns
        )
    ],
    remainder="passthrough"
)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [15]:
linear_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LinearRegression())
])

In [16]:
linear_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['area_type', 'location'], dtype='str'))])),
                ('model', LinearRegression())])

In [17]:
linear_predictions = linear_pipeline.predict(X_test)

In [18]:
mae = mean_absolute_error(y_test, linear_predictions)

rmse = np.sqrt(
    mean_squared_error(
        y_test,
        linear_predictions
    )
)

r2 = r2_score(
    y_test,
    linear_predictions
)

print(f"MAE : {mae:.2f}")

print(f"RMSE : {rmse:.2f}")

print(f"R² Score : {r2:.4f}")

MAE : 31.60
RMSE : 94.46
R² Score : 0.6479

In [19]:
tree_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", DecisionTreeRegressor(
        random_state=42
    ))
])

tree_pipeline.fit(X_train, y_train)

tree_predictions = tree_pipeline.predict(X_test)

In [20]:
tree_r2 = r2_score(
    y_test,
    tree_predictions
)

print(f"Decision Tree R² : {tree_r2:.4f}")

Decision Tree R² : 0.6140

In [21]:
forest_pipeline = Pipeline([
    (
        "preprocessor",
        preprocessor
    ),
    (
        "model",
        RandomForestRegressor(
            n_estimators=200,
            random_state=42
        )
    )
])

forest_pipeline.fit(
    X_train,
    y_train
)

forest_predictions = forest_pipeline.predict(
    X_test
)

In [22]:
forest_mae = mean_absolute_error(
    y_test,
    forest_predictions
)

forest_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        forest_predictions
    )
)

forest_r2 = r2_score(
    y_test,
    forest_predictions
)

print(f"MAE : {forest_mae:.2f}")

print(f"RMSE : {forest_rmse:.2f}")

print(f"R² : {forest_r2:.4f}")

MAE : 28.93
RMSE : 89.05
R² : 0.6871

In [23]:
xgb_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", XGBRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
        random_state=42
    ))
])

xgb_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['area_type', 'location'], dtype='str'))])),
                ('model',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              colsample_bytree=None, device=None,
                              early_stopping_rounds=N...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.05,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=6, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=300, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [24]:
xgb_predictions = xgb_pipeline.predict(X_test)

In [25]:
xgb_mae = mean_absolute_error(y_test, xgb_predictions)

xgb_rmse = np.sqrt(
    mean_squared_error(y_test, xgb_predictions)
)

xgb_r2 = r2_score(y_test, xgb_predictions)

print(f"MAE  : {xgb_mae:.2f}")
print(f"RMSE : {xgb_rmse:.2f}")
print(f"R²   : {xgb_r2:.4f}")

MAE  : 28.49
RMSE : 89.65
R²   : 0.6829

In [26]:
cat_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", CatBoostRegressor(
        iterations=300,
        learning_rate=0.05,
        depth=6,
        verbose=0,
        random_state=42
    ))
])

cat_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['area_type', 'location'], dtype='str'))])),
                ('model',
                 CatBoostRegressor(depth=6, iterations=300, learning_rate=0.05, loss_function='RMSE', random_state=42, verbose=0))])

In [27]:
cat_predictions = cat_pipeline.predict(X_test)

In [28]:
cat_mae = mean_absolute_error(y_test, cat_predictions)

cat_rmse = np.sqrt(
    mean_squared_error(y_test, cat_predictions)
)

cat_r2 = r2_score(y_test, cat_predictions)

print(f"MAE  : {cat_mae:.2f}")
print(f"RMSE : {cat_rmse:.2f}")
print(f"R²   : {cat_r2:.4f}")

MAE  : 29.09
RMSE : 85.51
R²   : 0.7115

In [29]:
results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost",
        "CatBoost"
    ],
    "R2 Score": [
        r2,
        tree_r2,
        forest_r2,
        xgb_r2,
        cat_r2
    ]
})

results.sort_values(
    by="R2 Score",
    ascending=False
)

               Model  R2 Score
4           CatBoost  0.711460
2      Random Forest  0.687073
3            XGBoost  0.682867
0  Linear Regression  0.647874
1      Decision Tree  0.613983

In [30]:
from sklearn.model_selection import RandomizedSearchCV

In [31]:
params = {
    "model__max_depth": [3, 4, 5, 6, 7],
    "model__learning_rate": [0.01, 0.03, 0.05, 0.1],
    "model__subsample": [0.7, 0.8, 0.9, 1.0],
    "model__colsample_bytree": [0.7, 0.8, 0.9, 1.0],
    "model__n_estimators": [200, 300, 500]
}

In [32]:
xgb_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", XGBRegressor(
        random_state=42,
        objective="reg:squarederror"
    ))
])

In [33]:
random_search = RandomizedSearchCV(
    estimator=xgb_pipeline,
    param_distributions=params,
    n_iter=20,
    cv=5,
    scoring="r2",
    random_state=42,
    n_jobs=-1,
    verbose=2
)

random_search.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.1, model__max_depth=7, model__n_estimators=500, model__subsample=0.8; total time=   0.5s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.03, model__max_depth=7, model__n_estimators=500, model__subsample=0.7; total time=   0.5s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.1, model__max_depth=7, model__n_estimators=500, model__subsample=0.8; total time=   0.5s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.03, model__max_depth=7, model__n_estimators=500, model__subsample=0.7; total time=   0.5s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.03, model__max_depth=7, model__n_estimators=500, model__subsample=0.7; total time=   0.5s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.03, model__max_depth=7, model__n_estimators=500, model__subsample=0.7; total time=   0.6s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.1, model__max_depth=7, model__n_estimators=500, model__subsample=0.8; total time=   0.6s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.03, model__max_depth=7, model__n_estimators=500, model__subsample=0.7; total time=   0.6s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.03, model__max_depth=7, model__n_estimators=200, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.03, model__max_depth=7, model__n_estimators=200, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.03, model__max_depth=7, model__n_estimators=200, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.03, model__max_depth=7, model__n_estimators=200, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.03, model__max_depth=7, model__n_estimators=200, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.05, model__max_depth=7, model__n_estimators=300, model__subsample=0.8; total time=   0.3s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.05, model__max_depth=7, model__n_estimators=300, model__subsample=0.8; total time=   0.3s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.1, model__max_depth=4, model__n_estimators=500, model__subsample=1.0; total time=   0.2s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.1, model__max_depth=7, model__n_estimators=500, model__subsample=0.8; total time=   0.5s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.1, model__max_depth=7, model__n_estimators=500, model__subsample=0.8; total time=   0.5s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.05, model__max_depth=7, model__n_estimators=300, model__subsample=0.8; total time=   0.3s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.1, model__max_depth=4, model__n_estimators=500, model__subsample=1.0; total time=   0.2s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.05, model__max_depth=7, model__n_estimators=300, model__subsample=0.8; total time=   0.3s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.05, model__max_depth=7, model__n_estimators=300, model__subsample=0.8; total time=   0.3s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.1, model__max_depth=4, model__n_estimators=500, model__subsample=1.0; total time=   0.2s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.1, model__max_depth=4, model__n_estimators=500, model__subsample=1.0; total time=   0.2s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.01, model__max_depth=4, model__n_estimators=500, model__subsample=0.8; total time=   0.2s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.1, model__max_depth=4, model__n_estimators=500, model__subsample=1.0; total time=   0.2s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.01, model__max_depth=4, model__n_estimators=500, model__subsample=0.8; total time=   0.2s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.01, model__max_depth=4, model__n_estimators=500, model__subsample=0.8; total time=   0.2s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.01, model__max_depth=4, model__n_estimators=500, model__subsample=0.8; total time=   0.2s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.01, model__max_depth=4, model__n_estimators=500, model__subsample=0.8; total time=   0.2s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.1, model__max_depth=5, model__n_estimators=500, model__subsample=1.0; total time=   0.2s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.1, model__max_depth=5, model__n_estimators=500, model__subsample=1.0; total time=   0.2s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.1, model__max_depth=5, model__n_estimators=500, model__subsample=1.0; total time=   0.2s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.1, model__max_depth=5, model__n_estimators=500, model__subsample=1.0; total time=   0.2s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.1, model__max_depth=5, model__n_estimators=500, model__subsample=1.0; total time=   0.2s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.03, model__max_depth=5, model__n_estimators=200, model__subsample=0.9; total time=   0.1s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.03, model__max_depth=5, model__n_estimators=500, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.03, model__max_depth=5, model__n_estimators=200, model__subsample=0.9; total time=   0.1s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.03, model__max_depth=5, model__n_estimators=500, model__subsample=0.9; total time=   0.3s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.03, model__max_depth=5, model__n_estimators=200, model__subsample=0.9; total time=   0.1s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.03, model__max_depth=5, model__n_estimators=500, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.03, model__max_depth=5, model__n_estimators=500, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.03, model__max_depth=5, model__n_estimators=200, model__subsample=0.9; total time=   0.1s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.03, model__max_depth=5, model__n_estimators=200, model__subsample=0.9; total time=   0.1s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.03, model__max_depth=5, model__n_estimators=500, model__subsample=0.9; total time=   0.3s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.05, model__max_depth=6, model__n_estimators=200, model__subsample=0.9; total time=   0.1s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.05, model__max_depth=6, model__n_estimators=200, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.05, model__max_depth=6, model__n_estimators=200, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.05, model__max_depth=6, model__n_estimators=200, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.05, model__max_depth=6, model__n_estimators=200, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=0.9, model__learning_rate=0.03, model__max_depth=6, model__n_estimators=200, model__subsample=0.7; total time=   0.1s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.03, model__max_depth=3, model__n_estimators=300, model__subsample=1.0; total time=   0.1s
[CV] END model__colsample_bytree=0.9, model__learning_rate=0.03, model__max_depth=6, model__n_estimators=200, model__subsample=0.7; total time=   0.2s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.03, model__max_depth=3, model__n_estimators=300, model__subsample=1.0; total time=   0.1s
[CV] END model__colsample_bytree=0.9, model__learning_rate=0.03, model__max_depth=6, model__n_estimators=200, model__subsample=0.7; total time=   0.2s
[CV] END model__colsample_bytree=0.9, model__learning_rate=0.03, model__max_depth=6, model__n_estimators=200, model__subsample=0.7; total time=   0.2s
[CV] END model__colsample_bytree=0.9, model__learning_rate=0.03, model__max_depth=6, model__n_estimators=200, model__subsample=0.7; total time=   0.2s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.03, model__max_depth=3, model__n_estimators=300, model__subsample=1.0; total time=   0.1s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.03, model__max_depth=3, model__n_estimators=300, model__subsample=1.0; total time=   0.1s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.03, model__max_depth=3, model__n_estimators=300, model__subsample=1.0; total time=   0.1s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.1, model__max_depth=6, model__n_estimators=200, model__subsample=0.9; total time=   0.1s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.1, model__max_depth=6, model__n_estimators=200, model__subsample=0.9; total time=   0.1s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.1, model__max_depth=6, model__n_estimators=200, model__subsample=0.9; total time=   0.1s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.1, model__max_depth=6, model__n_estimators=200, model__subsample=0.9; total time=   0.1s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.1, model__max_depth=6, model__n_estimators=200, model__subsample=0.9; total time=   0.1s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.1, model__max_depth=7, model__n_estimators=300, model__subsample=1.0; total time=   0.2s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.1, model__max_depth=7, model__n_estimators=300, model__subsample=1.0; total time=   0.2s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.1, model__max_depth=7, model__n_estimators=300, model__subsample=1.0; total time=   0.2s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.1, model__max_depth=7, model__n_estimators=300, model__subsample=1.0; total time=   0.2s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.1, model__max_depth=7, model__n_estimators=300, model__subsample=1.0; total time=   0.2s
[CV] END model__colsample_bytree=0.9, model__learning_rate=0.03, model__max_depth=6, model__n_estimators=300, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=0.9, model__learning_rate=0.03, model__max_depth=3, model__n_estimators=200, model__subsample=0.9; total time=   0.1s
[CV] END model__colsample_bytree=0.9, model__learning_rate=0.03, model__max_depth=3, model__n_estimators=200, model__subsample=0.9; total time=   0.1s
[CV] END model__colsample_bytree=0.9, model__learning_rate=0.03, model__max_depth=3, model__n_estimators=200, model__subsample=0.9; total time=   0.1s
[CV] END model__colsample_bytree=0.9, model__learning_rate=0.03, model__max_depth=6, model__n_estimators=300, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=0.9, model__learning_rate=0.03, model__max_depth=6, model__n_estimators=300, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=0.9, model__learning_rate=0.03, model__max_depth=3, model__n_estimators=200, model__subsample=0.9; total time=   0.1s
[CV] END model__colsample_bytree=0.9, model__learning_rate=0.03, model__max_depth=3, model__n_estimators=200, model__subsample=0.9; total time=   0.1s
[CV] END model__colsample_bytree=0.9, model__learning_rate=0.03, model__max_depth=6, model__n_estimators=300, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=0.9, model__learning_rate=0.03, model__max_depth=6, model__n_estimators=300, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.01, model__max_depth=5, model__n_estimators=300, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.01, model__max_depth=5, model__n_estimators=300, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.01, model__max_depth=5, model__n_estimators=300, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.01, model__max_depth=5, model__n_estimators=300, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=0.7, model__learning_rate=0.01, model__max_depth=5, model__n_estimators=300, model__subsample=0.9; total time=   0.2s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.03, model__max_depth=3, model__n_estimators=300, model__subsample=0.8; total time=   0.1s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.03, model__max_depth=3, model__n_estimators=300, model__subsample=0.8; total time=   0.1s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.03, model__max_depth=3, model__n_estimators=300, model__subsample=0.8; total time=   0.1s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.1, model__max_depth=6, model__n_estimators=500, model__subsample=0.7; total time=   0.3s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.03, model__max_depth=3, model__n_estimators=300, model__subsample=0.8; total time=   0.1s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.03, model__max_depth=3, model__n_estimators=300, model__subsample=0.8; total time=   0.1s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.1, model__max_depth=6, model__n_estimators=500, model__subsample=0.7; total time=   0.3s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.1, model__max_depth=3, model__n_estimators=500, model__subsample=0.7; total time=   0.2s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.1, model__max_depth=6, model__n_estimators=500, model__subsample=0.7; total time=   0.4s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.1, model__max_depth=3, model__n_estimators=500, model__subsample=0.7; total time=   0.2s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.1, model__max_depth=6, model__n_estimators=500, model__subsample=0.7; total time=   0.3s
[CV] END model__colsample_bytree=0.8, model__learning_rate=0.1, model__max_depth=6, model__n_estimators=500, model__subsample=0.7; total time=   0.4s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.1, model__max_depth=3, model__n_estimators=500, model__subsample=0.7; total time=   0.1s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.1, model__max_depth=3, model__n_estimators=500, model__subsample=0.7; total time=   0.1s
[CV] END model__colsample_bytree=1.0, model__learning_rate=0.1, model__max_depth=3, model__n_estimators=500, model__subsample=0.7; total time=   0.1s

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(remainder='passthrough',
                                                                transformers=[('cat',
                                                                               OneHotEncoder(handle_unknown='ignore'),
                                                                               Index(['area_type', 'location'], dtype='str'))])),
                                             ('model',
                                              XGBRegressor(base_score=None,
                                                           booster=None,
                                                           callbacks=None,
                                                           colsample_bylevel=None,
                                                           colsample_bynode=None,
                                                           colsample_bytree=None,
                                                           d...
                                                           multi_strategy=None,
                                                           n_estimators=None,
                                                           n_jobs=None,
                                                           num_parallel_tree=None, ...))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'model__colsample_bytree': [0.7, 0.8,
                                                                    0.9, 1.0],
                                        'model__learning_rate': [0.01, 0.03,
                                                                 0.05, 0.1],
                                        'model__max_depth': [3, 4, 5, 6, 7],
                                        'model__n_estimators': [200, 300, 500],
                                        'model__subsample': [0.7, 0.8, 0.9,
                                                             1.0]},
                   random_state=42, scoring='r2', verbose=2)

In [34]:
print("Best Parameters:")
print(random_search.best_params_)

Best Parameters:
{'model__subsample': 0.8, 'model__n_estimators': 500, 'model__max_depth': 4, 'model__learning_rate': 0.01, 'model__colsample_bytree': 0.8}

In [35]:
best_model = random_search.best_estimator_

predictions = best_model.predict(X_test)

r2 = r2_score(y_test, predictions)

print(f"Optimized XGBoost R² Score: {r2:.4f}")

Optimized XGBoost R² Score: 0.6922

In [36]:
import joblib
from pathlib import Path

model_dir = Path("../models")
model_dir.mkdir(parents=True, exist_ok=True)

joblib.dump(best_model, model_dir / "best_model.pkl")

print("Optimized model saved successfully!")

Optimized model saved successfully!